action_dim: 4
batch_size: 128
buffer_size: 5000
eps_decay_frac: 0.8
eps_end: 0.05
eps_start: 1.0
gamma: 0.9807306814170286
grad_clip: 1.0
hidden_dim: 256
learning_rate: 0.00010257563974185662
num_episodes: 2000
num_layers: 2
override_threshold: 2.5
reward_type: sortino
seed: 42
sortino_target_return: 0.0
sortino_window: 20
state_dim: 9
target_update: 100
test_start_date: '2024-01-01'
train_end_date: '2023-12-31'
